import Head from 'next/head'
import { useState } from 'react'
//import { getServerSideProps } from './api/todos'
import { getStaticProps } from './api/todos2'

import styled from 'styled-components'

const Container = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 100vh; /* 100% da altura da tela */
  padding: 0 0.5rem;
`

const TodoList = styled.ul`
  list-style: none;
  padding: 0;
  margin: 2rem 0;
  `
const TodoItem = styled.li`
  margin: 1rem 0;
  padding: 1rem;
  border: 1px solid #ccc;
  border-radius: 0.5rem;
  box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.1);
`
const TodoTitle = styled.h1`
  margin: 0;
  line-height: 1.15;
  font-size: 4rem;
  text-align: center;
  `

export default function Home({todos}) {
  // estamos iniciando todosState com conteúdo vindo do server side (NodeJS)
  const [todosState, setTodosState] = useState(todos)

 
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TodoTitle> Todos </TodoTitle>
      <TodoList>
        { todosState.map(todo => (
            <TodoItem key={todo.id}>
              <p> {todo.id} : {todo.title} </p>
            </TodoItem>
        )
          )
        }
      </TodoList>
    </Container>
  )
}

export { getStaticProps }